# Generated by Django 5.1 on 2024-08-23 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_city_user_document_number_user_person_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
    ]
