# Generated by Django 5.1 on 2024-09-17 14:17

import stdimage.models
import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image_profile",
            field=stdimage.models.StdImageField(
                blank=True,
                default=None,
                force_min_size=False,
                upload_to=users.models.get_file_path,
                variations={"thumb": {"crop": True, "height": 512, "width": 512}},
                verbose_name="Image Profile",
            ),
        ),
    ]
